### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by jakubgarfield** [mitul45/expense-manager#11]
What do you think about the ability to add expenses offline? We could leverage service workers and a cache for that.

**Comment by mitul45** [comment]
That's a good idea, but I haven't been able to implement service workers correctly (check #5). Need to fix that first.

As far as I can think, we would have to cache `expense` and whenever a network becomes available - make an API call. Still not sure how the first time authorization part would work.

**Comment by jakubgarfield** [comment]
@mitul45 I wouldn't worry about the first time authorization – that could be a hard requirement to be online (and you need to download the app somehow – so you probably are online already).

**Comment by mitul45** [comment]
Not the first time authorization. Whenever the app is initialized, the Sheets API makes a call to check the auth status. Something has to be done about that.
