### ISSUE TITLE
Date overlays the label in Chrome (Bug)

### ISSUE THREAD

**Issue by jakubgarfield** [mitul45/expense-manager#13]
When you launch the app it displays Date and current Date in the same input making it hard to read.

![screen shot 2017-05-13 at 10 14 03 am](https://cloud.githubusercontent.com/assets/194724/26018930/1655e130-37c6-11e7-9f58-1eb32f08ab36.png)

**Comment by jmcbee** [comment]
I'm experiencing this as well. Chrome 58.0.3029.96 (64-bit)

**Comment by mitul45** [comment]
I have seen this too. Thanks for pointing out.

**Comment by MrToWy** [comment]
same Issue in the new "Transfer" Tab :)

**Comment by MrToWy** [comment]
Fix:
remove this line from index.html:
`<label class="mdl-textfield__label" for="transfer-date">Date</label>`
