### ISSUE TITLE
how to deploy this on your own website.

### ISSUE THREAD

**Issue by nk932714** [mitul45/expense-manager#16]
i give a try to upload this code on my website but it shows loading no login page.

**Comment by mitul45** [comment]
I'm not sure what do you mean by "try to upload this code on my website", can you provide some more details?

To use the app – clone the expense sheet, visit: https://mitul45.github.io/expense-manager/, and log in with your Google account.

**Comment by nk932714** [comment]
I'm trying to host this repository on my website. Just for personal use. So what I've done to host this repo on my site.
1. I just cloned this repo.
2. changed the CLIENT_ID from [init.js](https://github.com/mitul45/expense-manager/blob/master/init.js) and put my own Google Sheets client ID
No login button appears. Just showing loading gif


I just wanna know that can i host this (https://mitul45.github.io/expense-manager/)[https://mitul45.github.io/expense-manager/] on my website too ?

**Comment by mitul45** [comment]
Ideally, that should be sufficient, are you getting any errors on the console?

**Comment by nk932714** [comment]
```Failed to load ‘https://www.google-analytics.com/analytics.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.```

**Comment by nk932714** [comment]
i think problem is here.

![image](https://user-images.githubusercontent.com/29853208/46848687-e57c7800-ce08-11e8-9cce-851f7658cb5b.png)

**Comment by nk932714** [comment]
![image](https://user-images.githubusercontent.com/29853208/46849509-5c1b7480-ce0d-11e8-9624-a08f0cf28664.png)

**Comment by wasi0013** [comment]
Did you find a solution to this? @nk932714 

I'm having the same issue:
It shows not a valid origin: 
```
{
    error: "idpiframe_initialization_failed", 
    details: "Not a valid origin for the client: https://wasi001…itelist this origin for your project's client ID."
}
```

**Comment by nk932714** [comment]
nope i haven't find any solution for this. @wasi0013

**Comment by cirio** [comment]
What's the command to build the project? Where is the output to upload on my host?
I changed CLIENT_ID in init.js and start index.html, but I've the same issue of others users.

**Comment by mitul45** [comment]
Hey everyone, sorry for the long delay in response.

So as I understand, you want to deploy this to some other static server, right? It should be doable by just copying everything from here and changing the CLIENT_ID in `init.js`. There is no build step it's all vanilla HTML/JS/CSS.

@nk932714 where did you get CLIENT_ID from? Also, note – it's not same as the Sheet ID.

**Comment by cirio** [comment]
@mitul45 It's ok, it's working

@wasi0013 have you add your hosting site in your allowed list for your project? You can do in google developer console. Also remember to add API to google Drive

**Comment by MeenachiSundaram** [comment]
@cirio @mitul45 

1. Can you please explain about CLIENT_ID, Where i can get that if it is not Sheet ID
2. Where to add API to Google Drive ?
3. What do you mean - "add your hosting site in your allowed list for your project"

**Comment by cirio** [comment]
@MeenachiSundaram :

1. You can find CLIENT_ID in your google developer console. After creating a project, on the credential panel, you can take a new client id  ([LINK](https://ibb.co/FWCF9Cm))

2) At the same place, in your google developer console. On the API & service tab, you can add a Google Sheets API and Google Drive API.

3) You can use Github or your custom domain as a hosting for your web site, so you need to add a new whished domain. ([LINK](https://ibb.co/b11PVv3))

 let me know if I can help you
