### ISSUE TITLE
Demo doesn't​ work Android phone

### ISSUE THREAD

**Issue by harshdeep21** [mitul45/expense-manager#3]
Demo doesn't​ work Android phone, not sure about other options though.

**Comment by mitul45** [comment]
Which Android version you were using? And which browser?

**Comment by harshdeep21** [comment]
Android 4.4.2
Xiaomi UI 8.0 bundled browser.

**Comment by mitul45** [comment]
@harshdeep21 can you check now? Last commit might have fixed it.

**Comment by harshdeep21** [comment]
Fantastic. Closing the issue.
