### ISSUE TITLE
Offer to create stylesheet 

### ISSUE THREAD

**Issue by Alonski** [mitul45/expense-manager#9]
Instead of showing an error why not create the stylesheet?

**Comment by mitul45** [comment]
I am not sure I understand. Do you mean instead of showing an error, I should create Google Sheet in user's Google Drive?

**Comment by Alonski** [comment]
Yea thats what I thought

**Comment by mitul45** [comment]
That's a good idea. Will see if I can pick up anytime soon. Thanks for the suggestion.

**Comment by Alonski** [comment]
Maybe I can look into this if I have time.

**Comment by Alonski** [comment]
When I did a GET to the current example `Expense Sheet` I got a really huge amount of JSON!
Any idea why this is?
[Google Spreadsheet.postman_collection.json.zip](https://github.com/mitul45/expense-manager/files/986212/Google.Spreadsheet.postman_collection.json.zip)

**Comment by mitul45** [comment]
I am not sure you need to `GET` the sheet. Probably you will have to take a look at the `copy` API: https://developers.google.com/drive/v3/reference/files/copy.

You will also need to update permissions to include `write permission` to Google Drive.

**Comment by Alonski** [comment]
Ok I just wanted to get a feel for what the create POST would look like. I will look into `copy`
